# Generated by Django 3.1.2 on 2020-10-19 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('game_mode', models.CharField(choices=[('assault', 'Assault'), ('control', 'Control (2 CP)'), ('escort', 'Escort'), ('hybrid', 'Hybrid'), ('push', 'Push')], max_length=15)),
                ('portrait', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('portrait', models.ImageField(null=True, upload_to='')),
                ('role', models.TextField(choices=[('tank', 'Tank'), ('damage', 'Damage'), ('support', 'Support')])),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('competitive_mode', models.CharField(choices=[('role_q', 'Role Queue'), ('open_q', 'Open Queue')], max_length=10)),
                ('played_role', models.CharField(choices=[('tank', 'Tank'), ('damage', 'Damage'), ('support', 'Support')], max_length=10)),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gamemap')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_sr', models.IntegerField(null=True)),
                ('tank_sr', models.IntegerField(null=True)),
                ('support_sr', models.IntegerField(null=True)),
                ('open_queue_sr', models.IntegerField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayedHeroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hero')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
    ]
