# Generated by Django 3.1.2 on 2020-10-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201019_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ('name',), 'verbose_name_plural': 'Heroes'},
        ),
    ]
