# Generated by Django 3.1.2 on 2020-10-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201019_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemap',
            name='game_mode',
            field=models.CharField(choices=[('assault', 'Assault (2 CP)'), ('control', 'Control'), ('escort', 'Escort'), ('hybrid', 'Hybrid'), ('push', 'Push')], max_length=15),
        ),
    ]
