# Generated by Django 3.1.2 on 2020-10-19 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201019_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='map_id',
            new_name='map',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='playedheroes',
            old_name='hero_id',
            new_name='hero',
        ),
        migrations.RenameField(
            model_name='playedheroes',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
